<?php

namespace LaraSpell\Generators;

use LaraSpell\Schema\Table;
use LaraSpell\Traits\TableDataGetter;

class ModelGenerator extends ClassGenerator
{

    use TableDataGetter;

    const CLASS_MODEL = 'Illuminate\Database\Eloquent\Model';

    protected $tableSchema;

    public function __construct(Table $tableSchema)
    {
        parent::__construct($tableSchema->getModelClass());
        $this->tableSchema = $tableSchema;
        $this->initClass();
    }

    protected function getTableSchema()
    {
        return $this->tableSchema;
    }

    protected function initClass()
    {
        $data = $this->getTableData();
        $fillables = $this->tableSchema->getFillableColumns();
        $this->setParentClass(static::CLASS_MODEL);
        $this->addProperty('table', 'string', 'protected', $data->table_name, 'Table name');
        $this->addProperty('fillable', 'array', 'protected', $fillables, 'Fillable columns');
        $this->addProperty('primaryKey', 'string', 'protected', $data->primary_key, 'The primary key for the model');
        $this->setDocblock(function($docblock) use ($data) {
            $authorName = $this->tableSchema->getRootSchema()->getAuthorName();
            $authorEmail = $this->tableSchema->getRootSchema()->getAuthorEmail();
            $docblock->addText("Generated by LaraSpell");
            $docblock->addAnnotation("author", "{$authorName} <{$authorEmail}>");
            $docblock->addAnnotation("created", date('r'));
        });
    }

}
